// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEDRjRF0FsBaZHaQ9bf5GldZUAdubNF0k',
    appId: '1:653600261605:web:34d162a1949cf23849db0c',
    messagingSenderId: '653600261605',
    projectId: 'a5-app-eb920',
    authDomain: 'a5-app-eb920.firebaseapp.com',
    storageBucket: 'a5-app-eb920.appspot.com',
    measurementId: 'G-VNFMRK5P7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7LNTxyrIG-m2gnS2WooqijwhwzuvZQYA',
    appId: '1:653600261605:android:24d1c893c3fe68e849db0c',
    messagingSenderId: '653600261605',
    projectId: 'a5-app-eb920',
    storageBucket: 'a5-app-eb920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTnmaqRZLlqxfkaUEcO_CqlHHBq5aG1i8',
    appId: '1:653600261605:ios:4e9b9c604a4bd67849db0c',
    messagingSenderId: '653600261605',
    projectId: 'a5-app-eb920',
    storageBucket: 'a5-app-eb920.appspot.com',
    iosClientId: '653600261605-pvcd8ms30ptii1pcgqjv5vti794ur4bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.a5App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTnmaqRZLlqxfkaUEcO_CqlHHBq5aG1i8',
    appId: '1:653600261605:ios:4e9b9c604a4bd67849db0c',
    messagingSenderId: '653600261605',
    projectId: 'a5-app-eb920',
    storageBucket: 'a5-app-eb920.appspot.com',
    iosClientId: '653600261605-pvcd8ms30ptii1pcgqjv5vti794ur4bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.a5App',
  );
}
